### ISSUE TITLE
update 2.0 

### ISSUE THREAD

**Issue by rachmadaniHaryono** [rachmadaniHaryono/Instant-Music-Downloader#1]
- [ ] drop support for python2.7 and python3.3
- [ ] fix c901 (too complex function.
- [ ] fix id3 tag
- [ ] use eyed3 0.8
- [ ] musicbrainz search
- [ ] beet integration.
- [ ] fix issue on upstream
  - [ ] #116 Optional Argument -f FILE [FILE . . .]
  - [ ] #113 [REQ] youtube playlist monitor
  - [x] #112 Permission Denied
  - [ ] #107 add a list/file maker to create a file for downloading
  - [ ] #102 Lyrics displaying html attributes
  - [ ] #93 try to add youtube autoplay feature in it enhancement
  - [ ] #89 Fix the name of the song after downloading
  - [ ] #78 Error while downloading
  - [ ] #70 TypeError: sequence item 0: expected str instance, bytes found
  - [ ] #69 'str' does not support the buffer interface
  - [ ] #63 Installation from source
  - [ ] #56 Graceful internet disconnection handling
  - [ ] #55 Pipe file to music player
  - [ ] #44 Fix pip Windows installation
  - [ ] #38 feature: Metadata
- [ ] merge upstream pr
  - [x] #114 Feature/py3 run 
  - [ ] #105 Added support for arch linux and redhat 
  - [ ] #103 Added the possibility to have a default output path 
  - [ ] #100 Ask for filename (defaults to current implementation) 
  - [ ] #96 Revert "Modifying requests to work with proxy" 
  - [ ] #91 pep8 & pyflakes 
  - [ ] #79 Add the ability to download an entire YouTube playlist and to set an output path 
  - [ ] #77 Fix output strings 
  - [ ] #74 Added requests to requirements.txt and setup.py 
  - [ ] #73 Add non unicode console support 
  - [ ] #67 Converted from using OS module to Subprocess 
  - [ ] #66 Added 10 Second Timeout, abort on error, and PEP'd some lines 
  - [ ] #64 Graceful handling of KeyboardInterrupt (Ctrl + C) 
  - [ ] #61 Implement issue #55 - added argument to launch a program 
  - [ ] #59 Reorder files and use standard setup.py config 
  - [ ] #33 os.system is bad, use subprocess so commands can't be injected 
  - [ ] #28 Select from multiple query results 
  - [ ] #26 converted to pep8 format
